export const departments = [
	{ id: '1', name: 'Ahuachapán' },
	{ id: '2', name: 'Cabañas' },
	{ id: '3', name: 'Chalatenango' },
	{ id: '4', name: 'Cuscatlán' },
	{ id: '5', name: 'La Libertad' },
	{ id: '6', name: 'La Paz' },
	{ id: '7', name: 'La Unión' },
	{ id: '8', name: 'Morazán' },
	{ id: '9', name: 'San Miguel' },
	{ id: '10', name: 'San Salvador' },
	{ id: '11', name: 'San Vicente' },
	{ id: '12', name: 'Santa Ana' },
	{ id: '13', name: 'Sonsonate' },
	{ id: '14', name: 'Usulután' },
]

export const municipalities: { [key: string]: string[] } = {
	Ahuachapán: [
		'Ahuachapán',
		'Apaneca',
		'Atiquizaya',
		'Concepción de Ataco',
		'El Refugio',
		'Guaymango',
		'Jujutla',
		'San Francisco Menéndez',
		'San Lorenzo',
		'San Pedro Puxtla',
		'Tacuba',
		'Turín',
	],
	Cabañas: [
		'Cinquera',
		'Dolores',
		'Guacotecti',
		'Ilobasco',
		'Jutiapa',
		'San Isidro',
		'Sensuntepeque',
		'Tejutepeque',
		'Victoria',
	],
	Chalatenango: [
		'Agua Caliente',
		'Arcatao',
		'Azacualpa',
		'Chalatenango',
		'Comalapa',
		'Concepción Quezaltepeque',
		'Dulce Nombre de María',
		'El Carrizal',
		'El Paraíso',
		'La Laguna',
		'La Palma',
		'La Reina',
		'Las Vueltas',
		'Nueva Concepción',
		'Nueva Trinidad',
		'Ojos de Agua',
		'Potonico',
		'San Antonio de la Cruz',
		'San Antonio Los Ranchos',
		'San Fernando',
		'San Francisco Lempa',
		'San Francisco Morazán',
		'San Ignacio',
		'San Isidro Labrador',
		'San José Cancasque',
		'San José Las Flores',
		'San Luis del Carmen',
		'San Miguel de Mercedes',
		'San Rafael',
		'Santa Rita',
		'Tejutla',
	],
	'San Salvador': [
		'Aguilares',
		'Apopa',
		'Ayutuxtepeque',
		'Ciudad Delgado',
		'Cuscatancingo',
		'El Paisnal',
		'Guazapa',
		'Ilopango',
		'Mejicanos',
		'Nejapa',
		'Panchimalco',
		'Rosario de Mora',
		'San Marcos',
		'San Martín',
		'San Salvador',
		'Santiago Texacuangos',
		'Santo Tomás',
		'Soyapango',
		'Tonacatepeque',
	],
}
